project:
  type: website

website:
  title: "sophie-a-lee.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: custom.scss
    toc: true



